apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2020-04-24T20:36:55Z'
  generation: 3
  labels:
    app: intranetanspedusv
  name: intranetanspedusv
  namespace: ansp
  resourceVersion: '17542613'
  selfLink: /apis/apps.openshift.io/v1/namespaces/ansp/deploymentconfigs/intranetanspedusv
  uid: 564e58ec-866b-11ea-953c-000d3a8c5974
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: intranetanspedusv
    deploymentconfig: intranetanspedusv
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: intranetanspedusv
        deploymentconfig: intranetanspedusv
    spec:
      containers:
        - image: >-
            docker-registry.default.svc:5000/ansp/intranet@sha256:1bea3c74e0b6178a6df6ff6833624ffd26d5ad0538baa6927bed9e7e3e9087ff
          imagePullPolicy: Always
          name: intranetanspedusv
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: intranet
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: intranet
          persistentVolumeClaim:
            claimName: intranet
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - intranet
        from:
          kind: ImageStreamTag
          name: 'intranetanspedusv:latest'
          namespace: ansp
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/ansp/intranetanspedusv@sha256:1bea3c74e0b6178a6df6ff6833624ffd26d5ad0538baa6927bed9e7e3e9087ff
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-04-24T20:37:13Z'
      lastUpdateTime: '2020-04-24T20:37:13Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-04-24T20:38:33Z'
      lastUpdateTime: '2020-04-24T20:38:36Z'
      message: replication controller "intranet-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
